src/generate_thumbnail.py
- Changed fitting behavior for characters in thumbnail: The characters now fill their allocated space in the thumbnail (See examples below)
=> Changed fitting behavior for characters in thumbnail

src/TSHScoreboardWidget.py
In reference to #74.
This simply drops the 2 lines in the reset score call that also resets the match and phase to blank. In a later release we can look to introduce a reset match button that'll clear out the phase and match as well, but this is more for a quick fix and release to get it out there.
=> Change Reset Score Button to not reset match and phase

src/thumbnail/main_generate_thumbnail.py
- Added backend options to disable force filling over X and Y axis of the characters in the thumbnail settings
- Currently are forced to True, will need backwards compatibility work in order to add those in settings file in future versions of TSH as well as UI work
=> Added backend for fill options in thumbnail

.github/workflows/gen_windows_release.yml
Apparently PyInstaller released 5.0 and it's breaking building for the moment, so this should fix it.
Something always has to ruin the party.
=> Add PyInstaller 4.10 specific versioning

src/TSHWebServer.py
One of my team members informed me of an edge case that could happen when using score up and down when swapping teams that could cause team 2 score up to affect team one and vice versa. This appeared to be linked more towards the State Manager getting confused when swapping players, but can't technically reproduce without the Web Server endpoints being used, so I've updated the calls to directly change the widgets to be more reliable in that aspect.
=> Changed score up and down for Web Server

src/TournamentDataProvider/SmashGGDataProvider.py, src/TournamentDataProvider/SmashGGRecentSetsQuery.txt
This PR addresses #102 with adding the ability to grab phase data and the round name and add it into the recent_sets overlay. Coming up with a proper layout for recent_sets will be something that I work with Shino on, but this gives the ability for pulling the information at least.
=> Added Phase data and Round name to Recent Sets Query

src/TSHTournamentDataProvider.py
Current challonge urls are now `challonge.com/<tournament>`.
This PR updates the Regular Expression to allow users to use Challonge again.
Current regular expression prevents users from using their tournaments because the regular expression is expecting another subdirectory, therefore locking users from hitting `Ok` to `Set Tournament`.
=> Bug Fix: Fix Challonge Regular Expression to Support Challonge Urls

layout/scoreboard_vgbootcampy/index.css
A really minor update: Increased padding-bottom of inner container from 16px to 17px to center phase and match properly within their container.
=> Minor Change: Centered Phase and Match in VGBC Overlay

src/StateManager.py
As the new changes broke data exporting, this fixes that issue by adding it back. Might see about a future PR for passing in the current state with the SaveState method to prevent this issue from happening again, as it seems that the StateManager was getting confused when trying to export and noticed no difference due to changes being saved.
=> Hotfix for TSH Data Exports

src/TSHThumbnailSettingsWidget.py, src/layout/TSHThumbnailSettings.ui, src/thumbnail/main_generate_thumbnail.py
- Fixed issue https://github.com/joaorb64/TournamentStreamHelper/issues/186: The assets are now centered by default if the zoom is smaller than 100%
- Added code to constrain the asset to certain borders if the scaled asset is smaller than the canvas
- To be used in a future feature, needs to be connected to the proper data. In this PR, the asset will not be constrained.
*Example of an asset with constraining borders on the left, right and bottom*
- Fixed an issue where the `(No game selected)` text in the UI would appear untranslated when resetting default settings for thumbnails
- Moved zoom option in the thumbnail settings tab
=> Thumbnail generator improvements

src/TournamentDataProvider/StartGGDataProvider.py, src/TournamentDataProvider/StartGGTournamentDataQuery.txt, src/layout/TSHTournamentInfo.ui
Basic PR that adds the ability to display and store the short link of the current selected event if the current event has one established, otherwise it'll return as blank. Should allow for a little bit more creativity in layouts with displaying event info.
**NOTE:** The new label for the QT layout will need translations for other languages to support the multi-language feature of TSH.
=> Added Short Link Functionality to TSH Tournament Info

src/TSHScoreboardPlayerWidget.py, src/TSHScoreboardWidget.py
This was always bothering me with the last sets PR I made that I couldn't make it originally per player to grab the stats and that I had to make it require both players before it could make the call.
Now after a couple weeks of brainstorming and realizing my mistake, I present this PR! This PR fixes my original issue with last sets and opens the doors to even more flexibility when it comes to adding features that can be individualized per player, such as, last sets, player tournament standings (keep an eye out for this one ;D ), and other cool features of the like! It allows features to be closer developed on a per player basis than an overall requirement of deciphering which ID changed where and what all is happening. This makes it simple by adding a player1ID and player2ID signal to …
=> Upgraded Player ID Signals to Support Individual Changes

src/TSHGameAssetManager.py
- Fixed metadata parsing for Splatoon 3 asset packs
- Now supports locale in metadata
- Dropped support for skin-specific metadata temporarily
=> Fixed metadata parsing

layout/tournament_history/index.js, src/TSHPlayerDB.py, src/TSHScoreboardPlayerWidget.py, src/TSHScoreboardWidget.py, src/TSHStatsUtil.py, src/TSHWebServer.py, src/TournamentDataProvider/StartGGDataProvider.py, src/TournamentDataProvider/StartGGEntrantsQuery.txt, src/TournamentDataProvider/StartGGPlayerTournamentHistoryQuery.txt, src/TournamentDataProvider/StartGGSetQuery.txt
- Shifted existing stats to new utility class for easier expansion and additions.
- Added Start Date to History Standings for a little more info of when it completed.
- Will need to add to current overlay.
- Potentially adding it as a faded background object on the layout would work for it. (Like the sponsor logo on the Top 8 layout)
- Added ability to recall stats via TSHWebServer for potential live updating down the line.
- This is more if the data is slightly out of date. (Ex. new set was completed that we can pull)
- Started base for Upset Factor and Seeding Performance Rating addition.
- Added additional bug fix as sometimes the Player ID was still not getting exported, it should now _hopefully_ be fixed.
=> Shifted Stats Functions to Separate Utility Class

src/TSHTournamentInfoWidget.py
This addresses #320 to match current locale date formatting. This will obviously need more testing and I think relies more on current OS locale, but is definitely less of a headache than other ways I looked into
=> Use Current Locale Date Format

src/TSHScoreboardWidget.py
This addresses the status of widget items not being transferred down to new players when the player amount per team is increased. This fix should now iterate the elements list to toggle the items when the player amount changes.
Apologies if this isn't that great, I just wanted to make a PR for it quick via GitHub over making a new branch and copying the fix over.
=> Transfer Player Item Toggle Status

.github/workflows/build_app.yml
GitHub has been putting slightly tedious messages to update workflows that used the set-output variables to a new method as they are sunsetting that way by the end of May. This adjusts the 2 places we use it to use the new method.
This was tested on one of my other forks and appears to be working as intended.
=> Fixes Tedious Error on Build

src/TSHScoreboardPlayerWidget.py, src/TSHScoreboardWidget.py
This addresses a flaw that was found where swapping player positions and teams would cause the seed variable to not swap as expected. This was tested by shifting players up and down on their own team, and swapping teams to make seeds do properly cross to the other team.
=> Fixes Player Seeds not swapping when switching teams

src/TSHScoreboardPlayerWidget.py
Currently there appears to be an issue that happens when teams are swapped with players that have character data assigned, which causes TSH to outright crash. I am not sure if this is the approach that we want to use to fix it, but at least in my testing, this does appear to not cause the crash any more.
Note: The crash can be averted with character amounts set to 0 for the time being
=> Fixes a crash when swapping players

layout/scoreboard_mainstagy/index.css, layout/scoreboard_mainstagy/index.js
Updated so that the big sponsor logo is now properly centered behind the small sponsor logo. Also changed the border radius of logo container, dimension of losers containers, and travel distance of losers containers.
=> Minor positioning fixes for mainstagy

layout/scoreboard_vgbootcampy_classic/index.css, layout/scoreboard_vgbootcampy_classic/index.js, layout/scoreboard_vgbootcampy_neo/index.css, layout/scoreboard_vgbootcampy_neo/index.js
Hi, I made so that the name, sponsor, and losers have even spacings. I also cleaned up code for the Twitter/Pronouns and Match/Best of switching logic. Thanks!
=> Spaced name, sponsor, and losers evenly + improved Twitter/Pronouns and Match/Best of switching logic

.github/workflows/build_app.yml, src/TSHGameAssetManager.py
- Fixed asset metadata handling (Bug #352)
- Forced Git pipeline to be executed on `fix/` branches
=> Fixed asset metadata handling

src/thumbnail/main_generate_thumbnail.py
If the main logo is not selected as a valid file (it points to a file that isn't there, there is no file, or it points to a non-image file), the thumbnail now displays without the logo
=> allows thumbnail to be displayed without main logo per #267

src/thumbnail/main_generate_thumbnail.py
Missing thumbnail foreground files no longer cause an error per #267
=> allows thumbnails to be rendered with missing foreground file

src/TSHGameAssetManager.py, src/TournamentDataProvider/StartGGDataProvider.py
This PR fixes the issue we've been seeing as of yesterday (May 6th) where StartGG started returning None for authorizations out of nowhere. There is also a fix in this PR for the asset manager as games like SFV would cause TSH to crash on loading due to no assets being found, so now when we go to load game assets by setting game from StartGG or Challonge, we will wait for the game loader thread to finish loading everything before we tell TSH to execute asset loading.
=> Fix StartGG API Break and fix weird asset crash potential

src/TSHSelectSetWindow.py
Adds a simple option now to make it easier for people who only want to see sets in the set selector that has a complete pair (player/team 1 and player/team 2 identified). Mathias mentioned it, I quickly added it and it appears to work great.
=> Add chekbox to only show complete pairs when showing sets

layout/scoreboard_vgbootcampy/README.md, layout/scoreboard_vgbootcampy_classic/README.md, layout/scoreboard_vgbootcampy_neo/README.md
Hello, I updated the READMEs of vgbootcampy, vgbootcampy_classic, and vgbootcampy_neo overlays to have explanations on how they work and what information they display. I deleted the part explaining how to download an overlay file since these files are already in the layout folder. Thank you!
=> Edited README of vgbootcampy overlays to include overlay properties

.github/workflows/build_app.yml
Updated currently used actions to more current versions of them to remove notices on running workflows about deprecation, as well as making the build system only run when a file outside the layout folder is committed to the repo.
=> Update build file with newer verisons of actions

src/TSHStatsUtil.py, src/TournamentDataProvider/StartGGDataProvider.py, src/TournamentDataProvider/StartGGSetQuery.txt
This should relieve an issue that was reported in the Discord server about the wrong seed being pulled when loading a set. Now instead of relying on what we pull from StartGG every time, we will now store the seeds in the StartGGDataProvider class on pulling entrant data and pull from that list/dictionary as the player gets pulled again based on the player ID.
This can probably be something we use to help roll it into making a proper player dictionary for storing their data to pull instead of StartGG every time as well.
=> Pull Seed on Entrant data, store it and push as needed

layout/scoreboard/index.css, layout/scoreboard/index.js, layout/scoreboard/sf6_offline.html, layout/scoreboard/sf6_online.html
There are now 2 separate layouts for SF6:
- Offline: Just place chips on the sides of the screen, since there isn't anything under the player HP side towards the screen edges.
- Online: cover LP with seed, when available. Divided the container into 2 because of platform icon. Hide container when there's no Twitter or pronoun.
=> Improve SF6 layouts

layout/include/globals.js
Added a little class that allows you to store content and an associated html selector so that the content is later added through SetInnerHtml. In procedural layouts, where we need a loop to generate html, and then another loop for SetInnerHtml calls, this removes the need for that second loop, as you can simply store the content while generating the html, and then simply call .resolve() to have the content added automatically. 
Not really adding a feature, but making scripts potentially cleaner.
=> ContentResolver

layout/scoreboard_JinTracker/index.js
Hi, in a rare instance I noticed that the name doesn't get centered properly when the character image is shown. I think this was due to the name getting set before the character image placeholder space was set, so I reordered their order of execution. Thanks!
=> Minor fix on JinTracker: Reordered function execution to center player name

src/TSHScoreboardWidget.py, src/TSHWebServer.py
Was requested on Discord.
Added in the ability to reset player widgets from the web server to make quick swapping that much easier. Also allows us to get a little bit closer to making an external control app.
=> Add in ability to clear player widgets from web server

src/TSHGameAssetManager.py, src/TSHScoreboardWidget.py, src/TSHWebServer.py
This PR adds the ability to specify a set ID to call to the web server to have TSH load it remotely. This can be good if you want to manually prepare the calls before hand or do it from another PC (Also potentially a future web tool to interface with TSH). The only weird change is to checking against the "lastSetSelected" variable as this didn't appear to work properly when making calls as _technically_ the set ID can have letters making it a string for StartGG (See preview sets if a pool has not started yet), so I changed it to be string checking as it will be more reliable in cases like that and works with remote calling and selecting via the set selector.
Tested against GOML 2023 Melee and Ultimate with no real issues found when testing.
=> Add the ability to remotely call sets to load from the Web Server

src/TSHScoreboardWidget.py, src/TSHWebServer.py
Trying to fix #522 : now that the UpdateSetData has been updated and works only when provided a full set data (with a set id), the web app should not use this method, but rather a method that just updates the provided data without checking if it's "complete". 
I created a new method that just changes the score, and the web server calls it now.
=> attempt to fix webapp being unable to change score

src/TSHScoreboardWidget.py
This will fix the sound request with the thumbnail generator. Unfortunately it comes at the cost of no icon being shown on the message box, but fixing it further would require touching QT accessibility settings, so maybe we can return to it later on.
=> Change Info icon to NoIcon

src/TSHScoreboardManager.py, src/TournamentStreamHelper.py
Addresses the Scoreboard Manager to automatically create the first scoreboard for the user over doing it on program init. Also addresses a weird translation issue with the scoreboard manager not properly applying when changing languages.
=> Scoreboard Manager Initializing create the first scoreboard and translation fix

src/TSHScoreboardManager.py, src/TournamentStreamHelper.py
This apparently caused the main scoreboard to not translate properly, so this addresses that.
=> Undo initialization change for Scoreboard Manager to prevent a different issue

src/i18n/gen_translation_files.py
This is in relation to #289 and Mathias seeing an issue where it was unvanishing all the untranslated items in the linguist files. In theory, this will now check to see if a blank translation exists, and if so, it'll add back the vanished tag to hide it as expected.
=> Introduce potential fix to hide untranslated items

src/TSHWebServer.py, src/TournamentStreamHelper.py
The Flask module inside Python .exe will try to access sys.stdout and sys.stderr, which isn't defined, so this redirects the variable to loguru.
=> Fix stdout/stderr bug with Flask trying to reference it

layout/scoreboard/arms.html, layout/scoreboard/index.css, layout/scoreboard/mk1.html, layout/scoreboard/pocketbravery.html, layout/scoreboard/pokken.html, layout/scoreboard/skullgirls.html, layout/scoreboard/tekken8.html
- Added standard layouts for the following games:
- ARMS
- Mortal Kombat 1
- Tekken 8
- Skullgirls
- Pokkén Tournament DX
- Pocket Bravery
=> Added standard layouts for ARMS, Tekken 8, Mortal Kombat 1, Skullgirls, Pokkén Tournament DX, Pocket Bravery

src/i18n/TSH_de.ts, src/i18n/TSH_en.ts, src/i18n/TSH_es.ts, src/i18n/TSH_fr.ts, src/i18n/TSH_it.ts, src/i18n/TSH_ja.ts, src/i18n/TSH_pt-BR.ts, src/i18n/TSH_zh-CN.ts, src/i18n/TSH_zh-TW.ts, src/thumbnail/main_generate_thumbnail.py
# CHANGES
- The thumbnail generator now also generates the title and description as needed for video uploads on YouTube, PeerTube and the likes
- The character limit for titles matches YouTube’s
- Supports translations
- Saves the data as `{out_path}/{thumbnail_filename}_title.txt` and `{out_path}/{thumbnail_filename}_desc.txt`
```
SMASH EXP: LEVEL-UP!
Ultimate Bracket - 18/11/2023
Jeu : Super Smash Bros Ultimate
Top 8 - Grande Finale
SMB | Mario (Mario) contre SMB | Luigi (Luigi)
Stream produit avec Tournament Stream Helper : https://github.com/joaorb64/TournamentStreamHelper/releases
```
=> Added automated title and description generation to thumbnail generator

src/TSHColorButton.py
Small one line addition to address the color picker background being the same as the current color selected.
=> Adjust color dialog to be dark gray instead

dependencies/requirements.txt
So qdarktheme is unmaintained, woo! It means that it doesn't support 3.12, but someone did a PR to fix compatibility. Down the road that branch itself should probably be forked and referenced from TSH instead, but for now this works.
=> include hacky python3.12 fix

src/TSHStatsUtil.py, src/TSHTournamentDataProvider.py, src/TournamentDataProvider/StartGGDataProvider.py, src/TournamentDataProvider/TournamentDataProvider.py, src/i18n/TSH_de.ts, src/i18n/TSH_en.ts, src/i18n/TSH_es.ts, src/i18n/TSH_fr.ts, src/i18n/TSH_it.ts, src/i18n/TSH_ja.ts, src/i18n/TSH_pt-BR.ts, src/i18n/TSH_zh-CN.ts, src/i18n/TSH_zh-TW.ts
Currently, the start.gg/challonge videogame ID was only present in the state through the "game" key, which is used for TSH's game assets system. So basically if we don't have assets for the current videogame, its ID is not present anywhere in the state.  
These are two things that should be separated and that's what this PR does, by adding a "provider_videogame" key in the state, which contains the ID of the current videogame as returned by the provider API.  
This allows the tournament history layout to work even when you don't have assets for the current game, which was not possible before these changes.
=> Add provider's videogame ID in the state as soon as it's received, regardless of whether base assets are present for this game

.gitignore
In Windows, you can customize the icon of a specific folder, which creates a desktop.ini file inside that folder. Since committing that file is usually not something you want, I added desktop.ini to .gitignore, so people can have their own customized folder icon for TSH without interacting with git.
Probably the most useless PR so far but i really like customized folder icons
=> Adding desktop.ini to .gitignore

layout/stream_queue/index.js
this PR changes exactly two characters in the code which makes me feel a bit stupid
In layout/stream_queue/settings.json, changing "display.avatar" to false did nothing (avatar still showed), which is fixed
=> Fix : the stream_queue layout ignored it's avatar display setting

layout/scoreboard/index.css, layout/scoreboard/roa2.html, src/TSHGameAssetManager.py, src/TournamentDataProvider/ChallongeDataProvider.py, test/test_eyesights.py
- Added sample layout for Rivals 2
- Example: ![Screenshot 2024-06-15 16-37-10](https://github.com/joaorb64/TournamentStreamHelper/assets/1964201/c5633918-05f6-4e15-ab0e-da6d6f48502c)
- Fixes to Python syntax
=> Added sample layout for Rivals 2

src/TSHWebServerActions.py
`bool('false')` will always return `True`. Not the prettiest solution but it works
=> Fix broken losers argument in set API due to incorrect conversion from string to bool

layout/main.css, layout/scoreboard/index.js, layout/scoreboard_4by3/index.js, layout/scoreboard_JinTracker/index.js, layout/scoreboard_WellySmash/index.js, layout/scoreboard_artistic/index.js, layout/scoreboard_mainstagy/index.js, layout/scoreboard_pandastic/index.js, layout/scoreboard_simple/index.js, layout/scoreboard_topleft/index.js, layout/scoreboard_vgbootcampy/index.js, layout/scoreboard_vgbootcampy_classic/index.js, layout/scoreboard_vgbootcampy_neo/index.js, layout/scoreboard_vgbootcampy_waiting/index.js, layout/versus_screen/index.js
Added the "forceDefaultScoreColors" option for layout settings, which, when set to true, makes the layout ignore custom team colors exported by TSH (and use the default one, red and blue)
=> Option to force default team colors

src/TSHGameAssetManager.py, src/thumbnail/main_generate_thumbnail.py
- Added feature to differentiate between skin names and "alternate characters"
- "Alternate characters" are defined as a special skin which turns the character into a completely different character
- Alternate character names are exported to the program output, while regular skin names are not
- Skins are marked as alternate characters using the `is_different_character` attribute
- Fixed special character sequence for thumbnails
=> Added feature to differentiate between skin names and "alternate characters"

src/Helpers/TSHDirHelper.py
In case there's anything I missed to #784 (e.g. OS-specific paths being different) merge this, otherwise feel free to close. Takes current working directory over bundle dir if there's a file that exists, or else falls back to bundle temp dir
=> Fallback to local filesystem file if it exists

.gitignore, scripts/gen_release.ps1, scripts/gen_release.sh, src/Helpers/TSHCountryHelper.py, src/Helpers/TSHLocaleHelper.py, src/StateManager.py, src/TSHBracket.py, src/TSHScoreboardPlayerWidget.py, src/TSHScoreboardStageWidget.py, src/TournamentDataProvider/StartGGDataProvider.py, src/TournamentStreamHelper.py, src/i18n/TSH_de.ts, src/i18n/TSH_en.ts, src/i18n/TSH_es.ts, src/i18n/TSH_fr.ts, src/i18n/TSH_it.ts, src/i18n/TSH_ja.ts, src/i18n/TSH_pt-BR.ts, src/i18n/TSH_zh-CN.ts, src/i18n/TSH_zh-TW.ts
Use zipfile instead of tarfile + switch to release.zip updates on Windows, source code on every other platform
Update gen_release.sh/.ps1 to generate releases into release.zip for upload to GitHub
Fix the countries%2Bstates%2Bcities.json download error that's been around forever (os.rename will move the file as well)
Fix KeyError inside phasegroup logic
Set several error/critical to warnings instead to keep error log file size lower
Ignore files that don't exist but are created later (out/program_state.json, user_data/pronouns_list.txt, user_data/rulesets.json)
Ignore bracket KeyErrors for any brackets that aren't loaded
=> Use zipfile and prefer releases on Windows, other small fixes

src/TSHScoreboardWidget.py
Fixes this strange error the leads to only the round name, and no other data loading.
```
Traceback (most recent call last):
File "I:\TournamentStreamHelper\src\TSHScoreboardWidget.py", line 1075, in UpdateSetData
self.ChangeSetData(data)
File "I:\TournamentStreamHelper\src\TSHScoreboardWidget.py", line 938, in ChangeSetData
if data.get("isPools", False) is False and round_division > 6:
^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
Other people have reported this issue as well (I suspect it was the same issue [here](https://discord.com/channels/1012284618457759755/1012285180989415434/1299887956986953810))
=> Fix a strange case where round_division could be missing

layout/include/globals.js, src/TSHGameAssetManager.py, src/TSHScoreboardWidget.py, src/i18n/TSH_de.ts, src/i18n/TSH_en.ts, src/i18n/TSH_es.ts, src/i18n/TSH_fr.ts, src/i18n/TSH_it.ts, src/i18n/TSH_ja.ts, src/i18n/TSH_pt-BR.ts, src/i18n/TSH_zh-CN.ts, src/i18n/TSH_zh-TW.ts, src/thumbnail/main_generate_thumbnail.py
- Fixed scaling not being handled properly for cropped assets in thumbnails
- Fixed Qualification text not being processed properly when building the default match/phase options
- Fixed (L), (W) being displayed in the default match/phase options
- Average size is now taken from the asset pack configuration
- Delete the thumbnail data after posting it to Bluesky
=> Various fixes

src/Helpers/TSHAltTextHelper.py, src/TSHGameAssetManager.py, src/TSHPlayerDB.py, src/TSHScoreboardPlayerWidget.py, src/TSHThumbnailSettingsWidget.py, src/i18n/TSH_de.ts, src/i18n/TSH_en.ts, src/i18n/TSH_es.ts, src/i18n/TSH_fr.ts, src/i18n/TSH_it.ts, src/i18n/TSH_ja.ts, src/i18n/TSH_pt-BR.ts, src/i18n/TSH_zh-CN.ts, src/i18n/TSH_zh-TW.ts
- Added compatibility for variants
- A variant is defined as an element which can affect the player’s character or playstyle without being another full character or being specific to a certain character. These can include:
- Assist-only characters (e.g. Mortal Kombat 1, Idol Showdown, Fraymakers)
- "Groove" systems (e.g. Capcom VS SNK 2 grooves, Street Fighter 6 Classic/Modern controls, Street Fighter Alpha 3 -ISM system, KOF98UMFE Power modes, Street Fighter V V-Trigger & V-Skill combinations)
- Variants must be defined in the main `config.json` of the game
- Variant icons (for now) go into the `variant_icon` pack. Please note that only PNGs are supported
- PR for control styles in Street Fighter 6: https://github.com/joaorb64/StreamHelperAssets/pull/650
- Only one variant type is …
=> Added compatibility for variants

layout/scoreboard_JinTracker/index.css
Adjusted margin so player name is centered better in JinTracker overlay. Also deleted unused CSS.
=> Adjusted margin so player name is centered better in JinTracker overlay

assets/contributors.txt, src/TSHBracketWidget.py, src/TSHCommentaryWidget.py, src/TSHGameAssetManager.py, src/TSHPlayerListWidget.py, src/TSHScoreboardWidget.py, src/i18n/TSH_de.ts, src/i18n/TSH_en.ts, src/i18n/TSH_es.ts, src/i18n/TSH_fr.ts, src/i18n/TSH_it.ts, src/i18n/TSH_ja.ts, src/i18n/TSH_pt-BR.ts, src/i18n/TSH_zh-CN.ts, src/i18n/TSH_zh-TW.ts
- Added feature to automatically set the number of characters / players based on the game
- For instance, sets the character number to 3 when loading Capcom VS SNK 2, and the player per team counter to 4 when loading Splatoon 3
- Uses the "defaults" item in the base config
- If no defaults are found, the program resets the player and character count to 1 upon loading the game
=> Added feature to automatically set the number of characters / players based on the game

layout/tournament_history/index.js
When swapping players, the tournament_history layout disappears, due to an error with the gsap animation. This fixes that (by recreating the gsap timeline every time).
=> Fix animation in tournament_history

src/TSHScoreboardPlayerWidget.py, src/TournamentDataProvider/StartGGDataProvider.py
This has been implemented and tested on @ZombieHDGaming 's fork for a while now, hopefully looking to add this to the main branch so it can be seamlessly included into future releases. Adds a hidden city export for start.gg sets that can be accessed and displayed by custom layouts.
=> Add city hidden export for player data

assets/contributors.txt, src/TSHCommentaryWidget.py, src/TSHPlayerDB.py, src/TSHScoreboardWidget.py, src/TSHWebServer.py, src/TSHWebServerActions.py, src/TournamentStreamHelper.py, src/i18n/TSH_de.ts, src/i18n/TSH_en.ts, src/i18n/TSH_es.ts, src/i18n/TSH_fr.ts, src/i18n/TSH_it.ts, src/i18n/TSH_ja.ts, src/i18n/TSH_pt-BR.ts, src/i18n/TSH_zh-CN.ts, src/i18n/TSH_zh-TW.ts
Added two routes to the HTTP Server : 
- `/update-commentary-<caster>` (POST) : sets commentator data (passed as JSON body)
- `load-commentator-from-tag-<index>` : loads a commentator from their tag (passed as a request argument) using the same process as `scoreboard<scoreboardNumber>-load-player-from-tag-<team>-<player>`
=> Change commentators data through the HTTP server

.gitignore
Added all assets/*_tmp directories to gitignore, to avoid unnecessary annoyance when they survive deletion
=> Gitignoring temp assets dirs in case they stay somehow

src/Settings/SettingsWidget.py, src/Settings/TSHSettingsWindow.py, src/TSHColorButton.py, src/TSHScoreboardManager.py, src/TSHScoreboardWidget.py, src/TournamentStreamHelper.py
- The default team colors are now changeable via the Settings menu.
- Colors are now able to be used as settings!
- The "Ok" button in the color picker dialog now displays as it should at long last.
- Fixed an oversight in hiding the player tracking feature (my bad).
=> Make Default Team colors changeable and add the ability to use colors in the settings widget

src/StateManager.py, src/TSHGameAssetManager.py, src/TSHPlayerList.py, src/TSHPlayerListSlotWidget.py, src/TSHPlayerListWidget.py, src/TSHScoreboardPlayerWidget.py, src/TSHScoreboardWidget.py, src/TournamentStreamHelper.py
Fixed issues arising from changing characters-per-player and players-per-team at the same time. This actually was a python bug rather than a web UI bug where the state got corrupted from zombie objects still firing their signals and updating state that had already been deleted. I also in the course of tracking this issue down added a context manager for StateManager.BlockSaving, since I started out thinking I was debugging an issue with the web UI getting out of sync.
The underlying issue was something like this: imagine you have something like a playerListWidget that holds a collection called self.playerWidgets, the list widget will delete them like so:
```
self.playerWidgets.remove(currentWidget)
currentWidget.deleteLater() # (a Qt method)
```
The problem with this, is that all the …
=> Fix players-per-team + characters-per-player causing state corruption

src/TSHGameAssetManager.py
- Changed custom zoom in UI for icons to 1.0
- This fixes an issue where sometimes uncropped icon assets are zoomed in too close in the UI to be distinguishable
=> Changed custom zoom in UI for icons to 1.0
