src/TSHScoreboardWidget.py

Hi there,
I've been keeping an eye on TSH 4.0 progress and have been putting in some testing for it as this is an awesome program!
I found this issue while testing and wanted to make a quick PR to get it in before an official release of 4.0. Apologies if this isn't a desired solution, this is my first time with Python coding. 😅
Feel free to let me know if this needs improved!

Fix bounds for Widget buttons

---

.gitignore
TSH_bat.bat
scripts/generate_thumbnail.py

- Prepared `generate_thumbnail.py` to support eyesight coordinates data
- Eyesight data will need to be available in `program_state.json` in order to be used

Added support for eyesight data in generate_thumbnail.py

---

scripts/generate_thumbnail.py

- Text will no longer overflow horizontally in a generated thumbnail. Instead, the text size will be reduced until it can fit whithin a given width

Added constraint on text width in the thumbnail script

---

test/test_eyesights.py

- Added debug script to draw eyesight corrdinates on the asset pack
- Debug images are saved in `out/test`

Added script to draw eyesight corrdinates on the asset pack

---

stage_strike_app/src/i18n/config.js
stage_strike_app/src/i18n/locales/en.json
stage_strike_app/src/i18n/locales/fr.json

- Added French localisation for stage strike app
- Added extra localisation data for stage strike app

Added French localisation for stage strike app

---

.github/workflows/gen_windows_release.yml
src/TSHScoreboardWidget.py

- Fixed an issue where the program would crash on boot if using Python 3.8
- Program now compiles using Python 3.8

Fixes for Python 3.8/Windows 7 compatibility

---

src/TSHWebServer.py

Didn't feel like putting this off until that feature is done being worked on, so ported fix to get it out there sooner.

Port fix from open sets PR

---

src/TSHWebServer.py

This was requested by my team member to move closer to full outside control of TSH.

Add Swap Teams Endpoint

---

layout/include/globals.js

- Fix to ensure the image always fills the canvas when used in layouts

Layouts: Made ratio consistent to fill the canvas

---

assets/pronouns_list.txt
src/TSHCommentaryWidget.py
src/TSHPlayerDB.py
src/TSHScoreboardPlayerWidget.py
src/TSHScoreboardWidget.py
src/layout/TSHCommentary.ui
src/layout/TSHCommentator.ui
src/layout/TSHScoreboardPlayer.ui

- Added basic support for pronouns for players and commentators
- TODO: Get pronouns data from Smash.gg

Added basic support for pronouns

---

assets/pronouns_list.txt
src/TSHCommentaryWidget.py
src/TSHScoreboardPlayerWidget.py

- Removed default pronouns list
- Pronouns are now saved in the user pronouns list when a player is saved to the local database

Refined pronouns feature

---

layout/include/globals.js

Changed centering behavior so that images always snap to canvas when too offset

---

src/thumbnail/main_generate_thumbnail.py

- Fixed several scaling issues in thumbnail generator
- Fixed separator not scaling properly with the background
- Fixed text outline not scaling properly with the background
- Scaling now uses LANCZOS algorithm, future plans include adding an advanced option to select the scaling algorithm in the UI
- This option may be irrelevant or different if we are to use QT and/or OpenCV for image processing instead

Fixed scaling issues in thumbnail

---

assets/thumbnail_base/thumbnail_types/type_a.json
src/thumbnail/main_generate_thumbnail.py

- Implement vertical switch for thumbnail info text

Implement vertical switch for thumbnail info text

---

src/thumbnail/main_generate_thumbnail.py

- Restored side icons on thumbnail

Restored side icons

---

assets/thumbnail_base/thumbnail_types/type_a.json
src/TSHThumbnailSettingsWidget.py
src/TournamentStreamHelper.py
src/thumbnail/main_generate_thumbnail.py

- Removed redundant value `["player_text"]["dimensions"]["x"]`
- Added value `["player_text"]["x_offset"]`
- Added values for `y_padding` for text
- Changed icon position in thumbnail type A to `bottom`
- Fixed the updater

Adjusted thumbnail description values

---

src/thumbnail/main_generate_thumbnail.py

- Fixed issue with thumbnail preview where the character name wouldn't be retained when disabling sponsor option
- Added easter egg

Fixed preview issues

---

src/TSHScoreboardWidget.py

- Added support for translated default match/phase lists

Added support for translated default match/phase lists

---

src/i18n/TSH_ja.ts

Hi, this is Justin/Jin. I created the Japanese translation! I would appreciate it if someone could review it and merge. Thanks!

Added Japanese translation

---

src/i18n/TSH_ja.ts

Hello, I made some changes to make the translations more accurate and concise. I would appreciate it if someone could review them. Thanks!

Made Japanese translation more accurate and concise

---

src/i18n/TSH_ja.ts

Found a translation error. Thanks!

Changed 'Players' to 'Number of Players'

---

src/i18n/TSH_ja.ts

Changed some translations so they sound more natural. Thanks!

Made Japanese translations more concise and natural

---

src/thumbnail/main_generate_thumbnail.py

- Added character translations to thumbnail preview

Added character translations to thumbnail preview

---

src/Helpers/TSHCountryHelper.py
src/Helpers/TSHLocaleHelper.py
src/TSHGameAssetManager.py
src/TSHScoreboardPlayerWidget.py
src/TSHScoreboardStageWidget.py
src/TSHScoreboardWidget.py
src/thumbnail/main_generate_thumbnail.py

- Base default locale for assets on current program locale instead of system locale
- Now asset locale defaults to program locale, then English

Base default locale for assets on current program locale instead of system locale

---

src/i18n/TSH_ja.ts

Hi, I added and updated Japanese translations. Thanks!

Added and Updated Japanese Translations

---

assets/contributors.txt
layout/top_8/index.js

Simply clears content when changing an item in the layout.

Fixed Top 8 Layout not reseting contents on change

---

src/thumbnail/main_generate_thumbnail.py

- Added constant scaling option for thumbnail generator
- Currently on by default, will need UI wiring

Added constant scaling option for thumbnail generator

---

src/TSHScoreboardPlayerWidget.py
src/TSHScoreboardWidget.py
src/TSHSelectSetWindow.py
src/TSHTournamentDataProvider.py
src/TournamentDataProvider/ChallongeDataProvider.py
src/TournamentDataProvider/StartGGDataProvider.py
src/TournamentDataProvider/StartGGUserSetQuery.txt
src/TournamentDataProvider/TournamentDataProvider.py
src/TournamentStreamHelper.py

Set selection improvements

---

src/TSHScoreboardWidget.py

Fix History Sets not being removed

---

layout/character_gallery/index.js

- Added custom centering and zoom support to character gallery

Added new features to character gallery

---

src/StateManager.py

Must be tested on OBS in Windows

Output assets as links

---

src/TSHBracketWidget.py
src/TSHSelectSetWindow.py
src/i18n/TSH_de.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts

- Fixed a crash that could occur from pressing OK in the set selector without selecting a set
- Set slot selector minimum for bracket creation to 2 to avoid having to create an impossible bracket

Fixed crashes

---

src/i18n/TSH_ja.ts
src/i18n/tournament_term/ja.json

Hi, I created a file called ja.json for Japanese tournament terms and added new translations to the TSH_ja.ts. Thanks!

Added Japanese Tournament Term File and New Translations to TSH_ja.ts

---

src/thumbnail/main_generate_thumbnail.py

Fixed bug 270

---

src/TSHPlayerListSlotWidget.py
src/TournamentDataProvider/StartGGDataProvider.py

Fix for https://github.com/joaorb64/TournamentStreamHelper/issues/262

Fix loading incomplete bracket phase

---

src/TSHTournamentInfoWidget.py

Not sure yet if it fixes the issue

Fix crash on invalid tournament

---

src/i18n/TSH_de.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts

- Added French localisation for Winners Only progression option

Update localisation for Winners Only progressions

---

layout/scoreboard_mainstagy/index.js

Hello, I made some constants to make the code less repetitive. Thanks!

Replaced frequently used numbers and strings with constants

---

layout/scoreboard_vgbootcampy_classic/index.css

Changed the background color of the container to white.

Changed background color of vgbootcampy classic container to white

---

layout/scoreboard_vgbootcampy_classic/index.css

Changed background-size of flag from cover to contain. Thank you!

Changed background-size of flag from cover to contain

---

layout/player_list/index.js

- Fix for bug #354 where the player list layout couldn't process teams properly

Fix `player_list` layout

---

src/TSHBracketWidget.py
src/layout/TSHBracket.ui

Adds the user the option to try again and fix https://github.com/joaorb64/TournamentStreamHelper/issues/260

Add button to update phases and phaseGroups

---

src/TournamentDataProvider/StartGGDataProvider.py

Fixes https://github.com/joaorb64/TournamentStreamHelper/issues/301

Fix unstarted StartGG bracket leading to random DQs

---

.gitignore
src/i18n/TSH_de.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts

- Fixed automated pipeline for locale file generation

Fixed locale regeneration

---

src/TSHScoreboardPlayerWidget.py

Fixes:
https://github.com/joaorb64/TournamentStreamHelper/issues/387
https://github.com/joaorb64/TournamentStreamHelper/issues/382

Fix persistent character skin selection

---

src/TSHGameAssetManager.py
src/TSHTournamentDataProvider.py
src/TSHTournamentInfoWidget.py
src/TournamentStreamHelper.py
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts

- Clears tournament variable
- Clears tournament data
- Clears tournament phases

Add unset tournament button

---

dependencies/requirements.txt
src/TSHAssetDownloader.py
src/TournamentStreamHelper.py
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts

- Set extra variables for Qt6 port to allow for images to load properly
- Fixed asset downloader menu

Set extra variables for Qt6 port

---

layout/top_n_list/index.js

Array generated should be correct but I only tested up to 128 players

Added standing formula for top_n_list

---

src/TournamentDataProvider/ChallongeDataProvider.py

- Added stability fixes for #423 
- Forced user agent for Challonge requests to be a Desktop instance of Firefox
- Added retry logic for initializing Cloudscraper
- TODO: Trigger a warning box if all retries fail

Added code to retry Cloudflare solving

---

src/TournamentDataProvider/StartGGDataProvider.py

Accidentally missed a big issue here to see if the player ID could be none, presumably due to a player not existing for a match yet (aka haven't progressed yet) when selecting/pulling a set. This should fix any issues that arise because of it.

Add check for seeds

---

src/TournamentDataProvider/StartGGDataProvider.py

Left a small mistake in the stream queue loading code, it crashed when there was no team. This is now fixed.

fix crash in stream queue loading

---

src/TSHPlayerDB.py
src/TSHScoreboardPlayerWidget.py

Now checks each main to see if it's a list with 2 entries; tries to parse the second entry as a skin *index* (integer), and if it doesn't work defaults to zero.
Fixes https://github.com/joaorb64/TournamentStreamHelper/issues/444

Fix saving and loading skins to local database

---

TSH.sh

Runs `pip install -r dependencies/requirements.txt` before running main.py to make sure deps are installed and up to date. If it's noisy we can pipe output to /dev/null

auto install reqs when running TSH.sh

---

src/Helpers/TSHCountryHelper.py
src/TournamentDataProvider/StartGGDataProvider.py

Self explanatory. I guess i somehow forgot to include that in the original PR ?

stream queue data now include player's state

---

layout/scoreboard_JinTracker/index.css
layout/scoreboard_JinTracker/index.js

Since all the texts are in uppercase, I removed every toUpperCase() method from the JS file and added text-transform: uppercase; in the CSS file instead to reduce repetition. Thanks to Seven and TwilCynder for pointing this out to me!

Minor fix: Uppercased text using CSS instead of JavaScript, No Visual Change

---

.github/workflows/build_app.yml
.gitignore

- Updated Python version to 3.11 as it should not impact OS compatibility when compared to 3.10

Updated Python to 3.11

---

src/TournamentDataProvider/StartGGDataProvider.py
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts

Title says all, GetStreamQueue was throwing an exception when no stream queue was found, this is fixed.

Small fix (stop the stream queue loading routine from throwing for no reason)

---

src/TSHTournamentDataProvider.py

Fixes https://github.com/joaorb64/TournamentStreamHelper/issues/477

Fix tournament provider hiccups clearing current set when tracking stream or user set

---

src/TournamentStreamHelper.py
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts

- Fixed `wolfy_fork/feature/additional_ui` being reverted due to erroneous merge
- Fixed init order causing the program not to start

Fixed `wolfy_fork/feature/additional_ui` being reverted due to erroneous merge

---

layout/stream_queue/index.js
layout/stream_queue/settings.json
src/TournamentDataProvider/StartGGDataProvider.py
src/TournamentDataProvider/StartGGStreamQueueQuery.txt
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts

- Fixed a bug preventing the stream queue from loading when there was no country data
- added an option to display only sets from the event selected in TSH (instead of the entire tournament)

Fix and improvement for the stream queue

---

src/TSHScoreboardWidget.py
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts

The stream queue is now loaded when the current set is auto-updated.
This is a temporary solution, before we add a proper interface for the stream queue with a refresh button and a start/stop auto-update button.

Auto-updating the stream queue

---

src/Settings/TSHSettingsWindow.py
src/StateManager.py
src/TSHScoreboardPlayerWidget.py
src/TSHScoreboardWidget.py
src/TournamentDataProvider/StartGGDataProvider.py
src/TournamentDataProvider/StartGGEntrantsQuery.txt
src/TournamentDataProvider/StartGGTournamentMainPhaseQuery.txt
src/TournamentDataProvider/StartGGTournamentSeedsQuery.txt

Adds critical logging for the StateManager to try and track down why the export issue is occurring for some users. This also includes the ability to disable automatic set updating for some users who don't need it or think it may help this issue.

Additional logging and setting for auto set updating

---

.github/workflows/build_app.yml

Fixes "ValueError: Invalid async_mode specified" on TSH startup

Update build process to include engineio in hidden import

---

src/TSHWebServer.py

It's in the title. Makes it so that exceptions log to files and not get lost in the console (esp if running from .exe)

Forward Flask logging and exceptions to loguru

---

src/thumbnail/main_generate_thumbnail.py

This addresses the issue relating to the original template that gets generated on software start not working and just being left as blank.

Fix template thumbnail not being properly generated

---

layout/scoreboard/index.css
layout/scoreboard/uni2.html
test/test_eyesights.py

- Added standard layout for the following game:
- Under Night In-Birth 2

Added standard layout for Under Night In-Birth 2

---

layout/scoreboard/gbvsr.html
layout/scoreboard/index.css
layout/scoreboard/nasb2.html

- Added template layout for Nickelodeon All-Star Brawl 2
- Added template layout for Granblue Fantasy Versus Rising

Added layouts for Nickelodeon All-Star Brawl 2 and Granblue Fantasy Versus Rising

---

layout/main.css
layout/scoreboard/index.js
layout/scoreboard_4by3/index.js
layout/scoreboard_JinTracker/index.js
layout/scoreboard_WellySmash/index.js
layout/scoreboard_artistic/index.js
layout/scoreboard_mainstagy/index.js
layout/scoreboard_pandastic/index.js
layout/scoreboard_simple/index.js
layout/scoreboard_topleft/index.js
layout/scoreboard_vgbootcampy/index.js
layout/scoreboard_vgbootcampy_classic/index.js
layout/scoreboard_vgbootcampy_neo/index.js
layout/scoreboard_vgbootcampy_waiting/index.js
src/TSHColorButton.py
src/TSHScoreboardWidget.py
src/TSHWebServer.py
src/TSHWebServerActions.py

Not the best at UI design so it could likely look better
Also changes the default colors to be closer to the SSBU P1 and P2 colors

Add custom color support

---

src/TSHBracketWidget.py
src/TSHWebServer.py
src/TSHWebServerActions.py

Currently only updates the first phase but I might come back to it and make it work with the selected phase

Add web request to update bracket

---

layout/scoreboard/dbfz.html
layout/scoreboard/index.css

- Added standard layout for DBFZ

Added standard layout for DBFZ

---

layout/scoreboard_WellySmash/icon_mic.svg
layout/scoreboard_WellySmash/index.css
layout/scoreboard_WellySmash/index.html
layout/scoreboard_WellySmash/index.js
layout/scoreboard_WellySmash/index_com.html

Add commentary overlay to WellySmash scoreboard

---

src/i18n/tournament_term/fr.json

- Update French localisation for qualifiers to better fit the context and machine insertion

Update French localisation for qualifiers

---

.gitignore
TSH.sh
TSH_bat.bat

- Changed SH and BAT script to use virtual environments instead of installing requirements in the local Python install

Changed SH script to use virtual environments

---

src/TSHScoreboardWidget.py
src/TSHWebServer.py
src/TSHWebServerActions.py

Requires #676 to be merged first

Add web request to load a player from the database from their tag

---

src/TSHWebServer.py

Add "no-mains" option to SocketIO "load-set"
Fix SocketIO "get-sets"

Misc SocketIO changes/fixes

---

src/TSHStatsUtil.py
src/TournamentDataProvider/StartGGDataProvider.py
src/TournamentDataProvider/StartGGPlayerLastSetsQuery.txt

- Add both players seed to the set data in last_sets. This allows showing things like upset factor in the last set layout

Add seed to last sets

---

src/TournamentDataProvider/StartGGDataProvider.py
src/TournamentDataProvider/StartGGSetQuery.txt

Makes it so new API can also pull current score, should the old API not return anything. Add additional checks to old API, as there was some issues noticed with it that may be leading to some of these issues.

Change over some items to also pull via newer StartGG API, add additional checks

---

src/TSHWebServer.py
src/TSHWebServerActions.py

Dunno if this is the best way to do this, but it works

Add get-match API request

---

src/TSHWebServer.py

This probably would've been smarter to add then `get-comms` (and I'm surprised it wasn't already a thing)

Add program state API call

---

src/Helpers/TSHCountryHelper.py
src/TSHGameAssetManager.py
src/TSHScoreboardPlayerWidget.py
src/TSHScoreboardWidget.py
src/TournamentDataProvider/ChallongeDataProvider.py
src/TournamentDataProvider/StartGGDataProvider.py
src/TournamentStreamHelper.py

Fix Python not liking certain line endings and stuff

How many times do we have to teach you this less old man?!

---

src/TSHScoreboardWidget.py
src/TournamentDataProvider/StartGGDataProvider.py

Includes cleanup for redundant variables

Change using lOverallPlacement with roundDivision for better Tournament Phase logic

---

layout/player_presentation/index.css
layout/player_presentation/index.js
layout/player_presentation/p1.html
layout/player_presentation/p2.html
layout/player_presentation/person.svg
layout/player_presentation/settings.json
layout/player_presentation/twitter.svg
layout/player_presentation/wifi.svg
layout/versus_screen/settings.json
layout/versus_screen_pokken/settings.json
layout/versus_screen_tekken8/settings.json
src/TSHGameAssetManager.py
src/TournamentStreamHelper.py
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts
test/test_eyesights.py

- Added support to load certain game assets when an alterate version is loaded from StartGG (e.g. Fighting EX Layer: Another Dash, Virtua Fighter 5 Ultimate Showdown)

Added support for alternate IDs in StartGG/Challonge

---

src/TSHScoreboardWidget.py

- Fixes issue https://github.com/joaorb64/TournamentStreamHelper/issues/808 where the Stream URL box would not be working as intended

Fix Stream URL text box not working

---

layout/include/globals.js

- Revert fix on scaled cropped assets for layouts due to many reports of it bugging out cropped assets even more

Revert fix on scaled cropped assets for layouts

---

layout/player_presentation/index.js

- Fixed an issue where the player presentation layout had the image of the currently selected stage

Fixed an issue where the player presentation layout has stage backgrounds

---

src/StateManager.py

Should fix images not updating in OBS

Export images with fresh metadata

---

layout/bracket/index.js
layout/bracket_ultimate/index.js
layout/player_list/index.js
layout/player_presentation/index.js
layout/scoreboard/index.js
layout/scoreboard_4by3/index.js
layout/scoreboard_JinTracker/index.js
layout/scoreboard_WellyRoA/index.js
layout/scoreboard_WellySmash/index.js
layout/scoreboard_artistic/index.js
layout/scoreboard_mainstagy/index.js
layout/scoreboard_pandastic/index.js
layout/scoreboard_roa2/index.js
layout/scoreboard_simple/index.js
layout/scoreboard_topleft/index.js
layout/scoreboard_vgbootcampy/index.js
layout/scoreboard_vgbootcampy_classic/index.js
layout/scoreboard_vgbootcampy_neo/index.js
layout/stream_queue/index.js
layout/stream_queue_simple/index.js
layout/top_8/index.js
layout/top_n_list/index.js
layout/versus_screen/index.js
layout/versus_screen_pokken/index.js
layout/versus_screen_tekken8/index.js

Addresses an issue reported on Discord about sponsor icons not showing for some people. Made sure ALL items in layouts using the URL in CSS functions now all have surrounding quotes to prevent issues.

Create consistency across layouts relating to images using URL in CSS

---

layout/scoreboard_JinTracker/index.css
layout/scoreboard_JinTracker/index.html
layout/scoreboard_JinTracker/index.js

I limited the size of the top left containers in JinTracker overlay.

Limited size of top left containers in JinTracker overlay

---

src/TSHGameAssetManager.py

- Added image size to data export
- Size data is extracted from the asset’s config file

Added image size to data export

---

src/TSHScoreboardWidget.py
src/TSHWebServer.py
src/TSHWebServerActions.py
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts

- Created new API path on the web server for get-thumbnail
- This API path will generate a thumbnail and then return the thumbnail which was just generated as a PNG or JPG, depending on what was requested

Created new API path for get-thumbnail

---

assets/contributors.txt
src/TSHBracket.py
src/TournamentDataProvider/ChallongeDataProvider.py
src/i18n/tournament_term/en.json
src/i18n/tournament_term/fr.json

- Added Losers Top 8 as a tournament term
- Needs mapping on StartGG

Added Losers Top 8 as a tournament term

---

src/TSHScoreboardPlayerWidget.py

- Added search function for skins, variants
- Most useful for games with named skins (Rivals of Aether II, Dragon Ball Sparking Zero, Mario Kart World) or lots of variants (Mortal Kombat 1, Mario Kart Double Dash, Idol Showdown)

Added search function for skins, variants

---

src/Helpers/TSHControllerHelper.py

- Added exporting of the simple controller icon when it exists

Added simple controller icon

---

src/TournamentStreamHelper.py
src/i18n/TSH_de.ts
src/i18n/TSH_en.ts
src/i18n/TSH_es.ts
src/i18n/TSH_fr.ts
src/i18n/TSH_it.ts
src/i18n/TSH_ja.ts
src/i18n/TSH_pt-BR.ts
src/i18n/TSH_zh-CN.ts
src/i18n/TSH_zh-TW.ts
stage_strike_app/src/i18n/locales/en.json
stage_strike_app/src/i18n/locales/fr.json

- Changed display name everywhere to "TournamentStreamHelper" for consistency

Changed display name everywhere to "TournamentStreamHelper" for consistency
